name       : libxpm
version    : 3.5.16
release    : 12
source     :
    - https://www.x.org/releases/individual/lib/libXpm-3.5.16.tar.gz : 43a70e6f9b67215fb223ca270d83bdcb868c513948441d5b781ea0765df6bfb4
license    : MIT
summary    : X Pixmap (XPM) image file format library
component  : xorg.library
builddeps  :
    - pkgconfig32(glib-2.0)  #check
    - pkgconfig32(x11)
emul32     : yes
optimize   : speed
description: |
    libXpm provides support and common operations for the XPM pixmap format, which is commonly used in legacy X applications. XPM is an extension of the monochrome XBM bitmap specified in the X protocol.
setup      : |
    %configure --disable-open-zfile \
               --disable-static \
               --enable-unit-tests
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
