name       : libxpm
version    : 3.5.14
release    : 11
source     :
    - https://www.x.org/releases/individual/lib/libXpm-3.5.14.tar.gz : 18861cc64dfffc0e7fe317b0eeb935adf64858fd5d82004894c4906d909dabf8
license    : MIT
summary    : X Pixmap (XPM) image file format library
component  : xorg.library
builddeps  :
    - pkgconfig32(x11)
emul32     : yes
optimize   : speed
description: |
    libXpm provides support and common operations for the XPM pixmap format, which is commonly used in legacy X applications. XPM is an extension of the monochrome XBM bitmap specified in the X protocol.
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
