name        : libxpm
version     : 3.5.11
release     : 5
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libXpm-3.5.11.tar.bz2 : c5bdafa51d1ae30086fac01ab83be8d47fe117b238d3437f8e965434090e041c
license     :
    - MIT
summary     : X Pixmap (XPM) image file format library
builddeps   :
    - pkgconfig(x11)
description : |
    libXpm provides support and common operation for the XPM pixmap format, which is commonly used in legacy X applications.  XPM is an extension of the monochrome XBM bitmap specificied in the X protocol.
    
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
