name       : libxpm
version    : 3.5.13
release    : 9
source     :
    - https://www.x.org/releases/individual/lib/libXpm-3.5.13.tar.gz : e3dfb0fb8c1f127432f2a498c7856b37ce78a61e8da73f1aab165a73dd97ad00
license    :
    - MIT
summary    : X Pixmap (XPM) image file format library
component  : xorg.library
builddeps  :
    - pkgconfig32(x11)
emul32     : yes
optimize   : speed
description: |
    libXpm provides support and common operation for the XPM pixmap format, which is commonly used in legacy X applications.  XPM is an extension of the monochrome XBM bitmap specificied in the X protocol.
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
